#!/bin/bash

set -euo pipefail

pluginDir=".semrel/$(go env GOOS)_$(go env GOARCH)/provider-gitlab/2.0.0/"
[[ ! -d "$pluginDir" ]] && {
  echo "creating $pluginDir"
  mkdir -p $pluginDir
}

go build -o $pluginDir/provider-gitlab ./cmd/provider-gitlab
